esp_toml_version = 1.0

firmware_images_url = "https://esp.kubaandrysek.cz/storage/arduino"

# Apps that you support and for which the binaries are available to publish.
supported_apps = ["BlinkRGB"]

image.esp32 = "BlinkRGB-esp32.bin"
image.esp32-s2 = "BlinkRGB-esp32-s2.bin"
image.esp32-s3 = "BlinkRGB-esp32-s3.bin"
